### ISSUE TITLE
Artillery Function test 

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR#30]
Does it work well?
What can be improved?

To do:
- [x] Add as placeable unit
- [x] Add line of sight capability
- [x] Add throttling capability
- [x] Add target down logic capability

**Comment by scooby78** [comment]
Fallback range and engagement range tweaked

**Comment by scooby78** [comment]
changes added ref: a0c88e1

**Comment by AmTheAgent** [comment]
This is still working well though under utilised i'd say! Only detraction is Spotter will act regardless of having 'Line of Sight' or not. Basically, he could be behind a sold rock on the terrain and still call in Arty.

**Comment by scooby78** [comment]
> Basically, he could be behind a sold rock on the terrain and still call in Arty.

I'll look into changing this

**Comment by scooby78** [comment]
wiki updated https://github.com/scooby78/160thSOR/wiki/Intelligent-Mortar-function

**Comment by scooby78** [comment]
script not finding targets in dedicated environment

**Comment by scooby78** [comment]
issues with dedicated server unit locality/ ownership

Although will work as editor placeable unit

**Comment by scooby78** [comment]
Test confirmed ok if editor placed

**Comment by scooby78** [comment]
351a04e794360abf76647a27a93d47355c2ff8dd
Fixes:
Issue noted with multiple Arti assets 
Removed requirement for group in loadouts
Removed requirement for defining Arti classname (simplified run-code)

**Comment by scooby78** [comment]
tested on dedicated server as editor placeable object ok
