### ISSUE TITLE
Vcom AI mod version test

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR#34]

**Comment by Nels0** [comment]
Are we still going to pursue this?
Feedback from missionmakers seemed to be that AI was more controllable using VCOM - despite aggression advantage.
Will try get more info from missionmakers.

**Comment by scooby78** [comment]
@Nels0 Please let me know your findings

**Comment by scooby78** [comment]
Any update on this?

**Comment by AmTheAgent** [comment]
I find the mod version even better than mission script version - there is more usable GUI for on the fly adjustments during missions if necessary. It can be easily enable/disabled at will - and at >2mb makes an easy add to the pack

**Comment by Nels0** [comment]
> **Vcom AI Changelog 2.81**
> *ADDED* AI have a better time following waypoints in combat.
> *ADDED* AI will more aggressively clear out buildings now.
> *ADDED* New settings in the userconfig file and VCOMAI_defaultsettings.sqf file for fine-tuning the queue system.
> *FIXED* AI assaulting a point sometimes would get stuck when AI deemed no cover was findable.
> *FIXED* Zeus controlled AI should now handle even better.
> *OPTIMIZED* Many functions and scripts heavily optimized.
> *OPTIMIZED* New queue system for AI taking cover and other HEAVY functions.
> **Vcom AI Changelog 9/11/2017 V2.91**
> *Fixed* AI will properly disembark vehicles, most of the time.
> *Changed* AI will now only call in an appropriate amount of reinforcements.
> *Changed* AI have a cooldown to how often they can call in reinforcements (per-region basis)
> *Fixed* AI will no longer hug the ground for the rest of their lives after combat. PTSD is a serious thing and proper therapy needs more funding.
> *Fixed* Aircraft transporting AI will now attempt to unload the troops, even if under fire. They used to wait until it was perfectly safe before.
> *Fixed* Config errors
> *Changed* VCOM In-game options dialog now only shows if you are an admin. It is now, by default, in the top right corner of the screen and will appear only if the player mouses over that area.

These look very promising and I'd like to test the mod again.

**Comment by scooby78** [comment]
I'll update the mod version on the server

**Comment by AmTheAgent** [comment]
I'm really having some great success testing this mod on the Test server - it's a game changer as far as AI skill goes. Perhaps Scooby, may be time to do a stress test with the mod version?

**Comment by Nels0** [comment]
Do we know which players need to have the VCOM mod loaded? If only Zeus &
Server need to have the mod loaded we could attempt this on a Sunday (after
researching/testing that of course). A Sunday is really the only likely way
to get a test with sufficient player numbers.

**Comment by yettie79** [comment]
at this stage, the AI spawners have done a great job. I think VCOM in not needed.

**Comment by scooby78** [comment]
I agree, I also think they fix more issues with Zeus desync (which I think is another issue with the ai) and allow the AI to be more controllable if needed..

The less addons the better..

@Nelso @AmTheAgent any further thoughts?

**Comment by AmTheAgent** [comment]
I agree. Current status of AI when you consider the spawners is more than adequate. The less addons the better.
