### ISSUE TITLE
M1117 speed buff

### ISSUE THREAD

**Issue by Diesel486** [scooby78/160thSOR#44]
regarding m1117 pro\ior to and after the latest update, m1117 is performing much better on road, though off-road has same performance being the main and major issue. suggest playing around with teraincoef to find the sweet spot.
many thanks for your efforts

**Comment by scooby78** [comment]
Interesting...  I saw almost double the off-road performance from a stand still and almost quadruple if you had a run up.

I had a look at your suggestion.  It's currently set to terrainCoef = 2.  From what I can research and from testing, this is a measure of how the power meets the ground (aka grip / wheel stickiness).  A lower number in my testing made for a poorer performance and and higher did similar as the tires now wouldn't let go of the road.

What test are you running and what where your results?
My tests from a standing position at the base of Military Hill yielded:
Base unit: Max speed of 18km/hr
Current unit: Max speed of 36km/hr
terrainCoef = 0: Max speed of 29km/hr
terrainCoef = 10: wouldn't move

With a run up from a road the current unit held 55 - 70km/hr up the hill and got air off the top.
