### ISSUE TITLE
Spawner

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR#51]
New function and scripted assets that allow mission makers to place down "fire and forget" spawners that will adapt to players and allow less requirements to micro manage missions. 

To do:

- [x] Make as placeable item 
- [x] Add ability to detect if player is down
- [x] Ability to adapt to multiple lines of attack 
- [x] Auto-shutoff if building is breached
- [x] Auto-shutoff is building is destroyed
- [x] Make 3DEN for Zeus placeable
- [x] Server monitoring logic to throttle AI spawning if FPS gets too low
- [ ] ~~Add menu system for variables to be adjusted easier~~ Moved to #83

**Comment by Diesel486** [comment]
recommend a rework of spawners, as observed in tonight's op they are almost impossible to put in an open-ish area, also if the terrain isn't level the Ai get stuck inside the buildings. would suggest making a rock or something as a spawner with a higher detection radius and mid to high numbers

**Comment by scooby78** [comment]
There is the 'invisible' spawner which is a rubbish pile..  That can be put inside existing buildings

Ref to do list above... it will have a menu to allow more dynamic operation including a spawn count selection

**Comment by Diesel486** [comment]
Out of curiosity, will the variables inclde an activation radius? This would be a massive help for situations where there is little defolaide in the 300m vacinity, a major issue I had on sunday's failop 😂

**Comment by scooby78** [comment]
yes it does :)

**Comment by scooby78** [comment]
grenade & RPG spam needs addressing through changes to group compositions

**Comment by scooby78** [comment]
Group compositions changed, range increased, spawn amount increased and grenades removed from most inf along with RPGs to avoid spamming.
