### ISSUE TITLE
CUP Terrains - Core Version 1.4.0

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR#52]
Config bin "HouseDestructionSmoke" error after certain buildings get destroyed
Requires CUP Terrains - Core Version 1.4.0 to fix.

**Comment by scooby78** [comment]
Confirmed to fix our "house destruction" error

In lieu of other new maps, do we want to leave out CUP - CWA ?
http://steamcommunity.com/sharedfiles/filedetails/?id=853743366

**Comment by Nels0** [comment]
I support removing CWA (I assume those are the really old maps, i.e Nogova and Old Malden), if it's a ~2GB saving or more. We have used them on occasion out of necessity, but if they're replaced by good maps, it's definitely worth it.
