### ISSUE TITLE
160th Weapon selector v1.5

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR#58]
https://github.com/destruktoid/Weapon-selector/releases/tag/1.5

**Comment by Ranger50** [comment]
the weapons are cool and all but they feel too similar in my opinion. Like they all sound the sound and feel the same and handle the same, the only difference is the name and maybe 1 skin. Would be cool to have guns which feel more different so it gives people that sense of uniqueness to their class and feels that their weapon can make a difference in battle. Or have more guns

**Comment by scooby78** [comment]
More guns means more types of ammo.  This will cause major supply issues and will allow for over powered weaponry, making it very hard (on top of an almost already impossible task)  for mission makers to balance missions well...  

Thank you for the feedback but this is more for bug reporting etc.

**Comment by Ranger50** [comment]
Ah ok. Well just saying that it doesn't need to be guns with different
calibers but I'm sure there are more 5.56 guns that we could use. I'm just
saying that the current guns we have look, sound and feel too similar to
each other

**Comment by scooby78** [comment]
Mech units reported not being able to use selector...

>  all the mech guys load out select dosnt work now, was in mission sunday and training space

**Comment by scooby78** [comment]
They have it just cant use drop down selection

**Comment by scooby78** [comment]
fixed in #65
