### ISSUE TITLE
160th Populator v0.3.2

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR#59]
https://github.com/destruktoid/Populate/releases/tag/0.3.2

**Comment by scooby78** [comment]
I think we need to put a limit on the area size that can be selected

**Comment by Nels0** [comment]
Would that be to limit the amount of AI spawned, or the impact on the server from calculating such a big area? 
A limit on AI spawned would definitely be a good idea (i.e 70-100 AI) just to prevent accidental overloading of the server if a mission maker puts a typo in etc.
If the area was limited, I believe that anything less than a ~1km diameter area would reduce the simplicity of using the mod.

**Comment by scooby78** [comment]
Maybe just the total amount of AI as a mission maker could easily spam the entire server with too many AI..

I think the issue will be how to implement the logic for this

**Comment by AmTheAgent** [comment]
The Populator Works Backwards to what i would expect.  ie: Last night, 10% would fill almost all slots in a building & 90% only a few - My logic says 10% = only populate 10% of available slots. (opposite to the way it was working essentially)

**Comment by scooby78** [comment]
Hmm, I can’t say I noticed that when I tested it.. interesting 

This was on Tanoa yeah?

**Comment by destruktoid** [comment]
Count is number of units per building - this is constant for every building in the area. Percentage is the % of buildings in the area that will have AI spawned in them.
