### ISSUE TITLE
Beketov Map

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR#79]
http://www.armaholic.com/page.php?id=31454 and also available on steam

**Comment by scooby78** [comment]
approved for Sunday missions

**Comment by Diesel486** [comment]
event feedback regarding beketov
 https://docs.google.com/spreadsheets/d/1PxyAf-QNreGGtl8RNnh4VNOfTsn0NoK6GAwcFQe3hGw/edit?usp=sharing
